FROM postgres:latest

# COPY database_info.sh /opt/database_info.sh

# RUN chmod +x /opt/database_info.sh && /opt/database_info.sh

# . psql -h localhost -U postgres -c "CREATE USER user WITH PASSWORD 'password';"